### ISSUE TITLE
matching test vectors?

### ISSUE THREAD

**Issue by itdaniher** [dkull/Isaac-CSPRNG#2]
Earlier, I verified that my Python3 update matches the output of the Python2 - that the first word produced with a null seed is '0x2343b9eb', but not that it matched the test vectors for the algorithm.

http://burtleburtle.net/bob/rand/isaacafa.html lists the mechanism for reproducing the test vectors 
 at http://burtleburtle.net/bob/rand/randvect.txt, and I've validated that the implementation of isaac in randport matches the listed test vector on my 64b machine.

```bash
wget http://burtleburtle.net/bob/c/randport.c http://burtleburtle.net/bob/c/rand.h http://burtleburtle.net/bob/c/standard.h
gcc -DNEVER -o isaac_randport randport.c
./isaac_randport | head -c 10
```
returns 
```
f650e4c8e4
```
Note that 'readable.c' produces different values than randport.c on my machine, which are also different from those produced by this Python code.

So - wondering what implementation this was based on, if at one point one one machine it produced the test vector, etc.

**Comment by dkull** [comment]
Hi, thanks for the interest, but this repo was created in the year 2010, so my memories of it are really faint.

But since I ported it from the ruby code in https://github.com/bai/crypt-isaac/, from date-matching it seems this was what I based it on: https://github.com/bai/crypt-isaac/blob/14dee014e73e0994ed45cf7ddbdc89ba69d6ba3d/lib/crypt-isaac/crypt-isaac.rb

I have memories of implementing several cryptography algorithms and I remember that I ran the test-vectors on at least some of them. I am not sure if I did it for this piece of code, hopefully, but I couldn't be sure.

**Comment by itdaniher** [comment]
Thanks for the response, and the information. And for putting your implementation on GH in the first place!

If I get some spare cycles I might try to printf debug the differences. 

It's worth noting that the rosettacode implementations give a different result from anything mentioned above, including the published vectors. It looks like there's a lot of subjectivity around the topic, which makes some sense given the age, revision count, and relative obscurity of the algorithm.

Thanks for your time!

**Comment by dkull** [comment]
The output now matches (one of the) reference ones.
